### ISSUE TITLE
remove package.browserify

### ISSUE THREAD

**Issue by cancerberoSgx** [Siddharth11/gradstop#14]
https://github.com/Siddharth11/gradstop/blob/0e37f29794588c6ead21e489f8a8ce470a985c04/package.json#L57

It's forcing me to install babelify, and several presets in my project in order to compile it with browserify. If you really need to provide a separate .js file for browsers, then compile it yourself and reference it using package.browser property instead. Thanks

**Comment by Siddharth11** [comment]
Currently, I don't have much time to work on this issue. Would you like to open a PR for this change?

**Comment by Siddharth11** [comment]
[Closing this issue](https://github.com/Siddharth11/gradstop/pull/15#issuecomment-489426954)
