### ISSUE TITLE
Publish to npmjs.com?

### ISSUE THREAD

**Issue by cymen** [Siddharth11/gradstop#4]
Will you publish this to npmjs.com for easy consumption? Also there is a typo in the name in the package.json here:

https://github.com/Siddharth11/gradStop.js/blob/master/package.json#L2

**Comment by cymen** [comment]
Ah! I looked closer and I see it will take a little bit of work to make it into a node module that can be consumed.

**Comment by Siddharth11** [comment]
@cymen Yep, it'll take some time. I'll try to work on it during this weekend. 
Let me know if you've any inputs :)

**Comment by antonedvard** [comment]
vote 1up here... would love to see this as an npm package :)

**Comment by Siddharth11** [comment]
Sorry for the late update @cymen @antonedvard.
I've published the [package on npm](https://www.npmjs.com/package/gradstop).
